import Link from "next/link";

const FirstSection = () => {
  return (
    <section className="md:pb-20 pb-10 bg-gradient-to-r from gray-00 to-gray-200 space-y-10">
      <div className="container mx-auto text-center">
        <div
          className="text-6xl flex justify-center font-bold md:px-20 pb-10
        text-gradient
        bg-gradient-to-r
        from-blue-500
        to-green-300
        bg-clip-text
        text-transparent"
        >
          Professional AI Headshots in minutes.
        </div>
        <p
          className="text-lg md:text-xl md-10
        bg-gradient-to-r
        from-black
        to-gray-400
        bg-clip-text
        text-transparent
        font-bold"
        >
          Elevate your online presence with HD headshots generated by our AI.
          Ideal for social profiles, resumes, and professional portfolios.
        </p>
        <div className="flex gap-4 justify-center pt-10">
          <Link href="/login">
            <button
              className="bg-blue-600 hover:bg-blue-500 text-white px-6 py-2 rounded-md text-lg font-bold
          transition transform hover:scale-105 motion-reduce:transition-none motion-reduce:hover:transform-none"
            >
              Get Your Headshots
            </button>
          </Link>
          <Link href="/login">
            <button
              className="bg-gray-600 hover:bg-gray-500 text-white px-6 py-2 rounded-md text-lg font-bold
          transition transform hover:scale-105 motion-reduce:transition-none motion-reduce:hover:transform-none"
            >
              Learn More
            </button>
          </Link>
        </div>
        <div className="pt-10">
          <video className="rounded-xl" autoPlay muted loop>
            <source src="/content/hero-1.mp4" type="video/mp4" />
          </video>
        </div>
      </div>
    </section>
  );
};

export default FirstSection;
